apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-backend
  template:
    metadata:
      labels:
        app: shopping-backend
    spec:
      containers:
      - name: shopping-backend
        image: umamaheswaritalupuri/shopping-backend:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: shopping-db
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password123
        - name: DB_NAME
          value: shopping
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-backend-service
spec:
  type: ClusterIP
  selector:
    app: shopping-backend
  ports:
    - port: 8000
      targetPort: 8000
